# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be5fe7341370d2860b05eafea264401c5fe3f9a7c3f97e73b4d14e265fa2ad2e76c4adacc60a8e665c3d4886fab18e23848ff3383a03a86c4b3a8398caa4dcd7

test:
  secret_key_base: 8d193d1c2fbc8f62e3dd947061c08eb8a69a686675aa776dfb91396b1a07b648f0dde39530ca4a99f37c3e8a6111e87e56e4376d18aa9c8d5d95f9abf148515d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
